### ISSUE TITLE
Panel does not load properly.

### ISSUE THREAD

**Issue by RealHotChiliPepe** [edvardpotter/outline-web-manager#1]
<img width="1381" alt="Снимок экрана 2023-07-29 в 8 53 04 PM" src="https://github.com/edvardpotter/outline-web-manager/assets/60117990/75b92337-01c4-4d01-a641-194338f9cb29">

It may be because I cloned the repository like so: git clone https://github.com/edvardpotter/outline-web-manager.git

**Comment by edvardpotter** [comment]
Can you send a screenshot from the browser developer panel (Console)?

**Comment by RealHotChiliPepe** [comment]
<img width="552" alt="Снимок экрана 2023-07-29 в 9 11 03 PM" src="https://github.com/edvardpotter/outline-web-manager/assets/60117990/91ea4f68-ae68-448c-b635-078989cca181">

**Comment by edvardpotter** [comment]
Thanks for your issue, I fixed it. Follow these steps:
Get the latest updates from the repository:
```shell
git fetch && git pull
```
Rebuild containers:
```shell
docker-compose up -d --build
```
After the containers are rebuilt, run:
```shell
docker exec outline-web-manager-php-1 bin/console assets:install
```

**Comment by RealHotChiliPepe** [comment]
Thanks a lot! I didn't even expect you to respond in the first place :)
I appreciate your work, this web manager is really helpful.

**Comment by edvardpotter** [comment]
Fixed

**Comment by edvardpotter** [comment]
Fixed
